# Minimal image for the TLS-terminating HTTP/1.1 forward proxy.
# The proxy uses only Node.js built-in modules, so no dependency install is needed.
FROM node:22-alpine

# openssl lets the entrypoint auto-generate a self-signed cert on first run.
RUN apk add --no-cache openssl

WORKDIR /app

# Copy only the files the server actually needs at runtime.
COPY package.json proxy.js config.js ./
COPY scripts/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

# certs/ holds the TLS key pair (mounted, or auto-generated by the entrypoint).
# Make it writable by the non-root "node" user.
RUN mkdir -p /app/certs \
    && chown -R node:node /app/certs \
    && chmod +x /usr/local/bin/docker-entrypoint.sh

ENV PROXY_HOST=0.0.0.0 \
    PROXY_PORT=6443 \
    PROXY_TLS=true \
    PROXY_TLS_CERT=/app/certs/proxy-cert.pem \
    PROXY_TLS_KEY=/app/certs/proxy-key.pem

EXPOSE 6443

USER node

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["node", "proxy.js"]
